Feature/#8/my test feature
Blobson/game-jam pull request #13
Opened 2023-03-15 18:00 UTC by Bartolemy12

2023-03-15 18:03 UTC, Blobson commented on ReadME.txt
> +sdfhasohdfgkas
Этот файл надо удалить

2023-03-15 18:03 UTC, Blobson commented on readMEEE.txt
> +sdafgashdgfhabsdkjfhabsdmb
Этот файл тоже надо удалить

2023-03-15 18:03 UTC, DemitrSpb requested changes

2023-03-15 18:03 UTC, DemitrSpb commented on ReadME.txt
> +sdfhasohdfgkas
лишний файл

2023-03-15 18:33 UTC, Blobson requested changes
Тебе надо сделать rebase на main и справиться с конфликтами.

2023-03-15 20:58 UTC, Blobson approved these changes

2023-03-15 21:05 UTC, Blobson approved these changes

2023-03-16 08:09 UTC, DemitrSpb approved these changes

2023-03-19 11:55 UTC, merged