#22/mainmenu. #23/settings
Blobson/game-jam pull request #28
Opened 2023-03-26 08:49 UTC by Svedmit

Главное меню
2 аудио шины для музыки и SFX
Меню настроек

2023-03-26 10:06 UTC, Blobson commented
Давайте сделаем папку `ui` и в неё будем складывать все файлы пользовательского интерфейса.
Также, предлагаю следовать [примеру](https://github.com/Blobson/game-jam/pull/26) @DemitrSpb - он для своего модуля сделал отдельную папку `TowerBuildLocation`. В данном случае думаю подойдёт папка `ui/MainMenu`.

2023-03-26 10:26 UTC, Blobson requested changes

2023-03-26 10:26 UTC, Blobson commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Давайте объекты называть максимально полно, чтобы не было недопониманий. Здесь лучше `Continue` выглядит немного неоднозначно. Лучше переименовать в `ContinueButton`.

2023-03-26 10:26 UTC, Blobson commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Нужно как-то проверять, что мы в режиме паузы и кнопка "Продолжить" видна и только тогда переводить на неё фокус.

2023-03-26 10:26 UTC, Blobson commented on main_menu.gd
> +	$CanvasLayer/Settings/SettingsElements/BackToMenu.grab_focus()
Зачем тут `grab_focus()`?

2023-03-26 10:26 UTC, Blobson commented on main_menu.gd
> +	$CanvasLayer/Settings/SettingsElements/BackToMenu.grab_focus()
Зачем тут `grab_focus()`?

2023-03-26 10:26 UTC, Blobson commented on settings.gd
> +	print(bus_index)
Давайте либо совсем уберём отладочный вывод, либо будем делать его правильно, с использованием [print-debug](https://docs.godotengine.org/en/latest/classes/class_@gdscript.html#class-gdscript-method-print-debug) и текстом типа `Music volume changed to ...`

2023-03-26 10:26 UTC, Blobson commented on main_menu.gd
> +func _on_back_to_menu_pressed():  #button BackToMenu in scene Settings/SettingsElement
Давай сделаем SettingsMenu отдельной сценой и этот метод перенесём в отдельный скрипт

2023-03-26 10:31 UTC, Svedmit commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Таким образом все кнопки переименовать?

2023-03-26 10:31 UTC, Svedmit commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Предлагаю сделать меню паузы отдельно.

2023-03-26 10:32 UTC, Svedmit commented on main_menu.gd
> +	$CanvasLayer/Settings/SettingsElements/BackToMenu.grab_focus()
На случай если ввод будет не только сенсорный.

2023-03-26 10:32 UTC, Svedmit commented on settings.gd
> +	print(bus_index)
Пардон, уберу.

2023-03-26 10:34 UTC, Svedmit commented on main_menu.gd
> +func _on_back_to_menu_pressed():  #button BackToMenu in scene Settings/SettingsElement
Так и хотел изначально, но если делать меню настроек отдельной сценой, тогда при переключении между сценами музыка будет начинаться заново. Если я все правильно понимаю.

2023-03-26 10:55 UTC, Blobson requested changes

2023-03-26 10:55 UTC, Blobson commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Желательно.

2023-03-26 10:55 UTC, Blobson commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Как вариант, но только наследуй его от MainMenu

2023-03-26 10:55 UTC, Blobson commented on main_menu.gd
> +func _on_back_to_menu_pressed():  #button BackToMenu in scene Settings/SettingsElement
С музыкой решим отдельно, но меню надо делать отдельными сценами

2023-03-26 10:57 UTC, Svedmit commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Добро, сделаю

2023-03-26 10:58 UTC, Svedmit commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Так и планировал, хорошо.

2023-03-26 10:58 UTC, Svedmit commented on main_menu.gd
> +func _on_back_to_menu_pressed():  #button BackToMenu in scene Settings/SettingsElement
Хорошо.

2023-03-27 07:10 UTC, Svedmit commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Исправлено

2023-03-27 07:12 UTC, Svedmit commented on main_menu.gd
> +	$CanvasLayer/Buttons/Continue.grab_focus() #Подсвечена кнопка 'продолжить' при запуске
Кнопка Продолжить в главном меню скрыта при отсутствии сохранений. Паузу сделал, от наследования пришлось отказаться, на встрече обсудим.

2023-03-27 07:30 UTC, Blobson requested changes

2023-03-27 07:30 UTC, Blobson commented on ui/MainMenu/main_menu.gd
> +var gamesaved: bool = 0 #наличие сохранений в игре. Когда игрок создаст сохранение, должна поменяться в 1.
Для булевых переменных нужно использовать `true/false`.

2023-03-27 07:30 UTC, Blobson commented on ui/PauseMenu/pause_menu.gd
> +extends Node2D
Мы же вроде договорились, что тут будет наследование от MainMenu?

2023-03-27 07:30 UTC, Blobson commented on ui/SettingsMenu/settings.gd
> +
Давайте уделять побольше внимание форматированию ;)
Здесь и чуть выше лишние пустые строчки нужно убрать.

2023-03-27 07:45 UTC, Svedmit commented on ui/SettingsMenu/settings.gd
> +
По две пустые строки между функциями же должно быть?

2023-03-27 07:45 UTC, Svedmit commented on ui/MainMenu/main_menu.gd
> +var gamesaved: bool = 0 #наличие сохранений в игре. Когда игрок создаст сохранение, должна поменяться в 1.
Исправил

2023-03-27 07:51 UTC, Svedmit commented on ui/PauseMenu/pause_menu.gd
> +extends Node2D
Да, я написал, что требует обсуждения. 
1. Мы наследуемся от main - там есть Новая игра которая нам не нужна.
2. По нажатии Продолжить в главном меню у нас открывается Уровень на котором мы остановились, а в Меню пауза он должен просто ставиться на паузу(process) и возобновляться по нажатию на Продолжить. Кнопки одни, а механизмы разные.
3. Нам нужен выход из игры в меню паузы?
4. Я не знаю другого механизма работы паузы, кроме как скрыть всю ноду и отобразить по нажатию на клавишу паузы, если здесь делать change_scene то уровень будет запускаться заново, а это же не совсем то что мы хотим? 

В общем я не совсем понимаю для чего нам тут наследование...

2023-03-27 18:22 UTC, Blobson commented on ui/MainMenu/main_menu.gd
> +var gamesaved: bool = 0 #наличие сохранений в игре. Когда игрок создаст сохранение, должна поменяться в 1.
А почему не залил?

2023-03-27 18:26 UTC, Blobson commented on ui/PauseMenu/pause_menu.gd
> +extends Node2D
Я вообще думаю, что надо при нажатии на паузу приостанавливать и сохранять игру и вываливаемся в Главное меню.

2023-03-28 02:36 UTC, Svedmit commented on ui/PauseMenu/pause_menu.gd
> +extends Node2D
То есть ты предлагаешь отказаться от меню паузы как такового? 
Я думал сделать базовую сцену level, и на ней сразу разместить паузу в invisible, какие-то основополагающие элементы и наследовать все уровни от него.
А сохранение тогда будет сохранять весь прогресс на уровне? 
Я думал сохранять только номер уровня. 
И как на счет того чтоб сделать в паузе рестарт уровня? Если человек видит что не правильно разместил башни, ему придется ждать конца уровня. Обычно в таких играх есть рестарт.

2023-03-28 02:42 UTC, Svedmit commented on ui/PauseMenu/pause_menu.gd
> +extends Node2D
И еще, сохранение будет одно? И только автоматическое? 
А если замахнемся на две концовки? :)
Можно после кнопки новая игра/продолжить делать change_scene_to страницу с тремя кнопками save. Для выбора сохранения. 
При первом запуске игры, когда save отсутствует - автоматом пишем в первый пустой слот.

2023-03-28 13:53 UTC, Svedmit commented
Ошибки исправил. Осталось решить что делать с паузой и нужна ли она нам в игре.

2023-03-28 16:01 UTC, Blobson commented on ui/PauseMenu/pause_menu.gd
> +extends Node2D
Да, отказаться от отдельного меню паузы, но только если это возможно.

Пока будем сохранять только номер уровня. Сохранять прогресс слишком геморно.

По поводу структуры:
```text
Game
 ├ UI
 │ ├ Menu
 │ │ └ MainMenu / SettingsMenu
 │ └ HUD
 ├ MusicPlayer
 └ CurrentLevel
   └ Level1
```
Так мы сможем не просто переключать сцены а в нужный момент включать выключать меню и не надо будет парится что музыка пропадает, потому как глобальный музыкальный плеер будет всегда цел.

2023-03-28 17:49 UTC, Blobson approved these changes

2023-03-28 18:35 UTC, Blobson approved these changes

2023-03-28 19:42 UTC, Blobson approved these changes

2023-03-28 19:43 UTC, DemitrSpb approved these changes

2023-03-28 19:44 UTC, merged