#19 Башня-пила
Blobson/game-jam pull request #35
Opened 2023-03-31 11:22 UTC by Svedmit

Башня должна по обнаружении врага включать анимацию пил, по нахождении врага в зоне пил башня отправляет сигнал с количеством урона. Башня может получать урон.

2023-03-31 14:41 UTC, Blobson requested changes

2023-03-31 14:41 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +@export var damage_taken: int = 2
Хотелось бы классу `Enemy` добавить параметр `attack_power` и использовать его.

2023-03-31 14:41 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +	print_debug("Signa 'damage_saw' = '{count}' in emit".format({
Ошибка в слове `Signal`.

2023-03-31 14:41 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +var enemy = null				  # НУЖНО ПРИВЯЗАТЬ ВРАГА
А если их несколько?

2023-03-31 14:41 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_observation_area_body_entered(body): #вход врага в поле зрения башни
Может лучше начинать работать когда враг подойдет в зону поражения?

2023-03-31 14:41 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_hit_box_body_entered(body): #получение урона башней (разрушение)
Это точно надо делать не здесь. У каждого врага будет своё расстояние и таймер атаки.

2023-03-31 14:41 UTC, Blobson commented on towers/defensive_towers/TowerSaw/texture/work/1.png
Текстуры с анимацией надо объединить в один файл. Много маленьких файлов сильно снизят производительность - это связано с особенностями работы видеокарт с памятью.

2023-04-01 12:07 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +var enemy = null				  # НУЖНО ПРИВЯЗАТЬ ВРАГА
Видел как делают глобальные классы для всех персонажей, но затрудняюсь тогда как сравнивать. Учитывая что body godot вообще не хочет ни с чем сравнивать

2023-04-01 12:09 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_observation_area_body_entered(body): #вход врага в поле зрения башни
Вообще по идее эти aria добавить бы в основной класс башни. Мне кажется логичным, что башня должна начинать наблюдать за врагами раньше, чем они войдут в зону поражения. На счет момента ее включения не уверен вообще.

2023-04-01 12:09 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_hit_box_body_entered(body): #получение урона башней (разрушение)
ХитБокс тоже убрать?

2023-04-01 12:11 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_observation_area_body_entered(body): #вход врага в поле зрения башни
Я вообще не уверен на счет данной механики повреждений по таймеру. Может разделить башню на низ и верх и пусть пила вытаскивается и крутиться постоянно, при этом когда будут столкновения пилы с врагами - она будет наносить повреждения. но тогда на пилу надо вешать маску коллизий и программировать ее движение.

2023-04-02 08:41 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +@export var damage_taken: int = 2
Переработано

2023-04-02 08:41 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +	print_debug("Signa 'damage_saw' = '{count}' in emit".format({
Переработано. От механики сигналов отказался

2023-04-02 08:42 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +var enemy = null				  # НУЖНО ПРИВЯЗАТЬ ВРАГА
Переработано

2023-04-02 08:42 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_observation_area_body_entered(body): #вход врага в поле зрения башни
Переработано. Пилы включаются по вхождению врага в их зону

2023-04-02 08:43 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_hit_box_body_entered(body): #получение урона башней (разрушение)
Разрушаемость пока остается под вопросом.

2023-04-02 08:44 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/texture/work/1.png
Сделано, но башня ползет. С объединением файлов в один, но с фреймами возникли проблемы. Виктория разбирается, у меня не на столько большой скилл фотошопа.

2023-04-02 16:04 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_hit_box_body_entered(body): #получение урона башней (разрушение)
С хитбоксом пока непонятки

2023-04-02 16:30 UTC, Blobson commented
Папку `work` c кучей отдельных текстур уже можно удалить?

2023-04-02 16:30 UTC, Blobson requested changes

2023-04-02 16:30 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +@export var attack_force: int = 5   #сила атаки башни
MINOR: Правильнее `attack_power`

2023-04-02 16:30 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_damage_area_area_entered(area):
Это хороший кандидат на перенос в BaseTower.

2023-04-02 16:30 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +		attack()
А почему бы `attack`  не вызывать из `_on_damage_area_area_entered` ?

2023-04-02 16:30 UTC, Blobson commented on units/enemies/Enemy/enemy.gd
> +@export var attack_force: int
`attack_power`

2023-04-02 16:30 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +var damaged_enemies = []     #враги в зоне пил
`enemies_in_damage_area`
Я зануда и буду поправлять неверный английский, сорян 🤷‍♂️ 😉

2023-04-02 16:30 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +	$DamageTimer.start(3.0)
`AttackTimer`, а то я долго думал зачем нам таймер повреждений 😉

2023-04-02 16:30 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_damage_area_area_entered(area):
Плюс, тут входной параметр не `area` а `node` или `body`.

2023-04-02 16:30 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +	if area.get_parent().has_method("take_damage"):
Я так понимаю так ты пытался определить, что в зону вошёл враг?

Кажется что правильнее будет в классе Enemy добавить:
```
func _init():
	add_to_group("enemies")
```
а здесь:
```
func _on_damage_area_area_entered(body):
    if body.is_in_group("enemies"):
        ...
```

2023-04-02 16:30 UTC, Blobson commented on units/enemies/Enemy/enemy.gd
> +
В дальнейшем тут надо что-то делать с `health <= 0`.

2023-04-02 20:55 UTC, DemitrSpb commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_damage_area_area_entered(area):
Параметр у сигнала правильный - `area`.

```
Signals

● area_entered(area: Area2D)Emitted when the received area enters this area. Requires monitoring to be set to true.
```

Только проблема в том, что у enemy нету `area`. У них только CollisionShape2D

2023-04-03 14:21 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_damage_area_area_entered(area):
Надо будет врагам навешивать area и туда уже пихать collisionShape. Потому что как я понял из body нельзя достучаться до базовой ноды.  А тогда вся механика пойдет по одному месту.

2023-04-03 14:23 UTC, Svedmit commented
> Папку `work` c кучей отдельных текстур уже можно удалить?

пока нет, еще пускай повисит. я удалю когда анимация точно будет работать как надо

2023-04-03 14:24 UTC, Svedmit commented on units/enemies/Enemy/enemy.gd
> +
в целом да, что-то типа remove node или скрывать и переносить на другой уровень столкновений. Разбирался с башней, в итоге задача от башни расширяется экспотенциально XD

2023-04-03 14:29 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +@export var attack_force: int = 5   #сила атаки башни
я думал вообще назвать по разному, например у башен attack_force, а у мобов attack_power, чтоб не путать. Или наоборот будет путаница и назвать одинаково и как ты сказал?

2023-04-03 14:31 UTC, Svedmit commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +		attack()
Я сделал наблюдение через delta во избежании всяких багов.

2023-04-05 11:35 UTC, Svedmit commented
Внес правки.

2023-04-07 07:50 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +@export var attack_force: int = 5   #сила атаки башни
Назвать одинаково

2023-04-07 07:51 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +func _on_damage_area_area_entered(area):
Тут вроде разобрались, что требуется использовать другой сигнал `body_entered` или что-то подобное.

2023-04-07 07:52 UTC, Blobson commented on towers/defensive_towers/TowerSaw/tower_saw.gd
> +	if area.get_parent().has_method("take_damage"):
Проверка правильная, но надо перейти на использование групп.

2023-04-07 07:54 UTC, Blobson commented on units/enemies/Enemy/enemy.gd
> +
Тут ты сделал всё верно. В дальнейшем надо будет просто заменять на спрайт разрушенной башни.

2023-04-07 07:54 UTC, Blobson submitted a review, later dismissed

2023-04-07 16:08 UTC, Bartolemy12 submitted a review, later dismissed

2023-04-08 18:56 UTC, merged