#56 ХП бар и рефакторинг атаки башен
Blobson/game-jam pull request #57
Opened 2023-04-11 16:51 UTC by VasyaLel

2023-04-11 19:40 UTC, DemitrSpb commented
![image](https://user-images.githubusercontent.com/38684545/231271060-9e355e2d-da09-45b9-88c9-92f460f7b8cf.png)
У меня такие ХП бары есть. Надо :)?

2023-04-12 10:30 UTC, VasyaLel commented
> ![image](https://user-images.githubusercontent.com/38684545/231271060-9e355e2d-da09-45b9-88c9-92f460f7b8cf.png) У меня такие ХП бары есть. Надо :)?

2023-04-12 10:32 UTC, VasyaLel commented
неплохо смотрится, думаю можно взять на вооружение, я чисто символически полоску хп добавил, чтоб была

2023-04-12 10:40 UTC, Blobson requested changes

2023-04-12 11:32 UTC, VasyaLel commented on ui/hp.png
не нужен, случайно закинул

2023-04-12 11:34 UTC, VasyaLel commented on units/enemies/Enemy/enemy.gd
> +	$HP_bar.set("value", (health/max_health)*$HP_bar.max_value)
поправил.
Убрал лишнюю переменную max_health, теперь вместо неё использую $Healthbar.max_value , который устанавливаю в _ready()

2023-04-12 11:34 UTC, VasyaLel commented on units/enemies/Mutant/mutant.tscn
> +[ext_resource type="Texture2D" uid="uid://d3n3m1kxytk2r" path="res://units/enemies/Enemy/hp.png" id="4_h40nx"]
Перенес

2023-04-12 14:39 UTC, Svedmit commented on towers/TowerSaw/tower_saw.gd
> +		elif enemies_in_damage_area.size() > 0:
Сюда тоже следует добавить debug:
print_debug("Something entered in my area:" + body.name)
если мы его используем. Иначе получится что дебаг печатается только один раз при входе первого противника, если я правильно понял логику.

2023-04-12 14:39 UTC, Svedmit commented on units/enemies/Mutant/mutant.gd
> +	health=health*2
Может нам лучше у enemy оставить пустой параметр health а в наследниках указывать int значение? иначе получиться что hp будет кратно значению родителя всегда

2023-04-12 16:03 UTC, VasyaLel commented on towers/TowerSaw/tower_saw.gd
> +		elif enemies_in_damage_area.size() > 0:
да, можно

2023-04-12 16:33 UTC, DemitrSpb commented on towers/TowerSaw/tower_saw.gd
> +			if enemies_in_damage_area.size() > 0:
тут проще код пишется
```
if body.is_in_group("enemies"):
    print_debug("Something entered in my area:" + body.name)
    enemies_in_damage_area.append(body)
    if enemies_in_damage_area.size() == 1:
        $Tower/AnimatedSprite2D.animation = "Work"
        attack()
```

2023-04-12 16:33 UTC, DemitrSpb commented on units/enemies/Enemy/enemy.gd
> +@export var move_speed: float = 150
speed, health это int

2023-04-12 16:35 UTC, DemitrSpb commented
> > ![image](https://user-images.githubusercontent.com/38684545/231271060-9e355e2d-da09-45b9-88c9-92f460f7b8cf.png) У меня такие ХП бары есть. Надо :)?
> 
> @DemitrSpb это надо всем

Ну дождусь мержа переделаю на свои

2023-04-12 16:51 UTC, Blobson requested changes

2023-04-12 18:10 UTC, Expert-3-line commented on towers/TowerSaw/tower_saw.gd
> +			if enemies_in_damage_area.size() > 0:
Согласен, поменял

2023-04-12 18:10 UTC, Expert-3-line commented on units/enemies/Enemy/enemy.gd
> +@export var move_speed: float = 150
Согласен, поменял на int

2023-04-12 18:11 UTC, VasyaLel commented on towers/TowerSaw/tower_saw.gd
> +			if enemies_in_damage_area.size() > 0:
согласен, поменял

2023-04-12 18:11 UTC, VasyaLel commented on units/enemies/Enemy/enemy.gd
> +@export var move_speed: float = 150
согласен, поменял

2023-04-12 18:11 UTC, VasyaLel commented on towers/TowerSaw/tower_saw.gd
> +		if enemies_in_damage_area.size() == 0:
согласен, поменял

2023-04-12 18:11 UTC, VasyaLel commented on units/enemies/Enemy/enemy.gd
> +@export var health: float = 50
Вернул int для health и move_speed

2023-04-12 18:11 UTC, VasyaLel commented on units/enemies/Enemy/enemy.gd
> +	$Healthbar.set("max_value,value", health)
согласен, поменял

2023-04-12 18:12 UTC, VasyaLel commented on units/enemies/Mutant/mutant.tscn
> +[node name="CollisionShape2D" parent="." index="1"]
поправил
![image](https://user-images.githubusercontent.com/127948581/231547104-ac0e2938-1d86-4197-9349-e5313230613d.png)

2023-04-12 18:21 UTC, Blobson approved these changes

2023-04-12 18:33 UTC, DemitrSpb approved these changes

2023-04-12 18:38 UTC, merged