#55 Индикатор зоны действия башни
Blobson/game-jam pull request #62
Opened 2023-04-14 08:51 UTC by Svedmit

Башня рисует зону при запуске, выглядит это просто ужасно! Думаю draw сюда вообще не подходит и это надо делать как-то иначе. Кроме того автоматизировать этот процесс крайне проблематично.

2023-04-15 10:11 UTC, Blobson requested changes

2023-04-15 10:33 UTC, Blobson requested changes

2023-04-15 10:33 UTC, Blobson commented on towers/TowerSaw/tower_saw.tscn
А ещё круче получается если вот такой scale сделать у CollisionShape2D или DamageArea
![image](https://user-images.githubusercontent.com/2709384/232208749-3962a7b2-863a-4e31-8a87-7b77829c3fa8.png)

2023-04-15 10:34 UTC, Blobson commented on towers/TowerSaw/tower_saw.tscn
Это кстати позволяет делать эллиптические CollisionShape. Также можно делать и у вражеских юнитов и у башен.

2023-04-16 07:31 UTC, Svedmit commented on towers/TowerSaw/tower_saw.gd
> +	draw_circle(Vector2(0, 32), radius_border, Color.ORANGE_RED)
Исправил! Это гениально!!!

2023-04-16 07:31 UTC, Svedmit commented on towers/TowerSaw/tower_saw.tscn
гм... неплохо

2023-04-17 16:23 UTC, DemitrSpb approved these changes

2023-04-18 21:13 UTC, Blobson requested changes

2023-04-18 21:13 UTC, Blobson commented on towers/TowerSaw/tower_saw.gd
> +		_draw()
Тут нельзя вызывать `_draw()`, его вызовет сам движок в нужный момент.

2023-04-18 21:14 UTC, Blobson requested changes

2023-04-18 21:14 UTC, Blobson commented on towers/TowerSaw/tower_saw.gd
> +@export var debug_area_circle: bool = true
Флаг я бы назвал `debug_damage_area`

2023-04-19 05:48 UTC, Svedmit commented on towers/TowerSaw/tower_saw.gd
> +		_draw()
А как тогда его включать и отключать? У меня был булева debug_area_circle, который экспортился и можно было включать-выключать draw.

2023-04-19 05:48 UTC, Svedmit commented on towers/TowerSaw/tower_saw.gd
> +@export var debug_area_circle: bool = true
Исправлю.

2023-04-21 10:48 UTC, Blobson approved these changes

2023-04-22 12:50 UTC, merged