#33 Прототип первого уровня с центрированием камеры
Blobson/game-jam pull request #69
Opened 2023-04-17 15:48 UTC by VasyaLel

2023-04-17 16:19 UTC, DemitrSpb commented on levels/Level1/level1_view.png
это вроде не нужно?

2023-04-17 16:23 UTC, DemitrSpb submitted a review, later dismissed

2023-04-17 16:52 UTC, DemitrSpb commented on levels/Level1/level1_view.png
Я тоже не знаю правильного ответа. Но меня запутало наличие 2-х картинок, долго искал где они используются

2023-04-17 17:26 UTC, Svedmit approved these changes

2023-04-18 21:19 UTC, Blobson requested changes

2023-04-20 15:10 UTC, VasyaLel commented on levels/Level1/level1_view.png
убрал

2023-04-21 10:46 UTC, Blobson approved these changes

2023-04-21 15:07 UTC, Svedmit submitted a review, later dismissed

2023-04-22 12:48 UTC, Blobson approved these changes

2023-04-22 12:51 UTC, merged