#92 Индикатор доступного золота
Blobson/game-jam pull request #94
Opened 2023-05-03 14:19 UTC by Svedmit

Добавил индикатор, золото падает за убийство врагов. Хотел запилить анимацию-интерполяцию но не получилось. +пофиксил кнопки абилок

2023-05-04 06:42 UTC, Blobson requested changes

2023-05-04 06:42 UTC, Blobson commented on game.gd
> +	Game.connect("gold_changed", $ui/GoldIndicator.change_value)
Вот это должно быть в `gold_indicator.gd`.

2023-05-04 06:42 UTC, Blobson commented on units/enemies/Enemy/enemy.gd
> +@export var gold_cost: int = 10
Давай переименуем в `gold_reward`

2023-05-05 16:34 UTC, Svedmit commented on units/enemies/Enemy/enemy.gd
> +@export var gold_cost: int = 10
Сделано.

2023-05-06 09:28 UTC, Blobson requested changes

2023-05-06 09:28 UTC, Blobson commented on ui/GoldIndicator/gold_indicator.gd
> +	var game = get_node("/root/Game")
А зачем `get_node("/root/Game")`?

2023-05-06 09:28 UTC, Blobson commented on ui/GoldIndicator/gold_indicator.gd
> +	var tween_indicator = create_tween()
Нельзя создавать новый tween на каждый сигнал об изменении золота. Лучше это сделать один раз в методе `_ready()`.

2023-05-06 09:31 UTC, Blobson commented
> Добавил индикатор, золото падает за убийство врагов. Хотел запилить анимацию-интерполяцию но не получилось. +пофиксил кнопки абилок
> 
> UPD.! Запилил анимацию. p.s. Tween в итоге создается каждый раз, т.к. он удаляется после проигрывания анимации. И если его поместить в @onready, или в _ready то он отрабатывает только один раз при запуске скрипта.

С чего ты взял, что tween удаляется после проигрывания анимации?

2023-05-06 09:36 UTC, Blobson requested changes

2023-05-06 09:36 UTC, Blobson commented on ui/GoldIndicator/gold_indicator.gd
> +@onready var tween_duration: float = 0.8
Этот параметр может быть константой и здесь не нужен `@onready`

2023-05-06 10:05 UTC, Svedmit commented on ui/GoldIndicator/gold_indicator.gd
> +@onready var tween_duration: float = 0.8
Это экспорт должен быть. Ошибся.

2023-05-06 10:05 UTC, Svedmit commented on ui/GoldIndicator/gold_indicator.gd
> +	var game = get_node("/root/Game")
Рудимент :) поправлю

2023-05-06 10:06 UTC, Svedmit commented on ui/GoldIndicator/gold_indicator.gd
> +	var tween_indicator = create_tween()
Поправлю.

2023-05-06 14:30 UTC, Blobson approved these changes

2023-05-06 18:02 UTC, merged